### ISSUE TITLE
Future roadmap

### ISSUE THREAD

**Issue by zmitry** [zmitry/storyui#2]
- [ ] Implement short url service
- [ ] Implement service for a snapshot testing
- [ ] plugin for react-query dev tools
